### PR TITLE
Initial pipeline setup

### PR DESCRIPTION
**Pull request by AvishrantsSh**
Signed-off-by: Avishrant Sharma <avishrants@gmail.com>

### CODE REVIEW

**Comment by AvishrantsSh** [comment]
The tests are failing because I've not set up the requirements yet. Is there any specific file/setting for that, or do I just use `install_requires` parameter? 
For now, the code is pretty much the same as used in https://github.com/nexB/scancode.io/pull/226.

Also, using this command worked just fine while testing
```sh
pip install git+https://github.com/nexb/scancode.io.git
```

**Comment by tdruez** [comment]
@AvishrantsSh I don't think we want to set scancodeio in the install_requires.
Instead, add the `pip install git+https://github.com/nexb/scancode.io.git` as a step in the ci configuration.

**Comment by tdruez** [comment]
Also, let's remove the travis conf and setup Github action instead for the tests.
See https://github.com/nexB/scancode.io/blob/main/.github/workflows/ci.yml for an example.

**Comment by AvishrantsSh** [comment]
While configuring the tests, I'm getting `ImproperlyConfiguredI` exception. It is probably because I'm trying to access `save_scan_file_results` method in the module.
```python
======================================================================
ERROR: tests.test_scancode_glc_plugin (unittest.loader._FailedTest)
----------------------------------------------------------------------
ImportError: Failed to import test module: tests.test_scancode_glc_plugin
Traceback (most recent call last):
  File "/usr/lib/python3.8/unittest/loader.py", line 436, in _find_test_path
    module = self._get_module_from_name(name)
  File "/usr/lib/python3.8/unittest/loader.py", line 377, in _get_module_from_name
    __import__(name)
  File "/home/avishrant/GitRepo/scancodeio.io-pipeline-glc_scan/tests/test_scancode_glc_plugin.py", line 6, in <module>
    from scancode_glc_plugin.pipes import glc
  File "/home/avishrant/GitRepo/scancodeio.io-pipeline-glc_scan/src/scancode_glc_plugin/pipes/glc.py", line 2, in <module>
    from scanpipe.pipes import scancode
  File "/home/avishrant/GitRepo/scancodeio.io-pipeline-glc_scan/lib/python3.8/site-packages/scanpipe/pipes/__init__.py", line 32, in <module>
    from scanpipe.models import CodebaseResource
  File "/home/avishrant/GitRepo/scancodeio.io-pipeline-glc_scan/lib/python3.8/site-packages/scanpipe/models.py", line 48, in <module>
    from packageurl.contrib.django.models import PackageURLQuerySetMixin
  File "/home/avishrant/GitRepo/scancodeio.io-pipeline-glc_scan/lib/python3.8/site-packages/packageurl/contrib/django/models.py", line 91, in <module>
    class PackageURLMixin(models.Model):
  File "/home/avishrant/GitRepo/scancodeio.io-pipeline-glc_scan/lib/python3.8/site-packages/django/db/models/base.py", line 108, in __new__
    app_config = apps.get_containing_app_config(module)
  File "/home/avishrant/GitRepo/scancodeio.io-pipeline-glc_scan/lib/python3.8/site-packages/django/apps/registry.py", line 253, in get_containing_app_config
    self.check_apps_ready()
  File "/home/avishrant/GitRepo/scancodeio.io-pipeline-glc_scan/lib/python3.8/site-packages/django/apps/registry.py", line 135, in check_apps_ready
    settings.INSTALLED_APPS
  File "/home/avishrant/GitRepo/scancodeio.io-pipeline-glc_scan/lib/python3.8/site-packages/django/conf/__init__.py", line 82, in __getattr__
    self._setup(name)
  File "/home/avishrant/GitRepo/scancodeio.io-pipeline-glc_scan/lib/python3.8/site-packages/django/conf/__init__.py", line 63, in _setup
    raise ImproperlyConfigured(
django.core.exceptions.ImproperlyConfigured: Requested setting INSTALLED_APPS, but settings are not configured. You must either define the environment variable DJANGO_SETTINGS_MODULE or call settings.configure() before accessing settings.
```

**Comment by tdruez** [comment]
@AvishrantsSh where can I see the ci configuration?
A traceback is not enough without the context.

**Comment by AvishrantsSh** [comment]
> @AvishrantsSh where can I see the ci configuration?
> A traceback is not enough without the context.

I'm testing this on my local machine, with
```sh
python -m unittest discover
```

**Comment by tdruez** [comment]
@AvishrantsSh since we depend on Django, you'll have to create a simple "test" settings file and define it before starting the test with `os.environ.setdefault("DJANGO_SETTINGS_MODULE", "tests.settings")` for example, or simply exporting the `DJANGO_SETTINGS_MODULE` envvar: `export DJANGO_SETTINGS_MODULE=test_settings`

**Comment by tdruez** [comment]
See also https://docs.djangoproject.com/en/3.2/topics/testing/advanced/#using-the-django-test-runner-to-test-reusable-applications and https://docs.djangoproject.com/en/3.2/intro/reusable-apps/

**Comment by AvishrantsSh** [comment]
@tdruez, I got the tests to work but I don't feel like it's the right way :P
I had to manually set `DJANGO_SETTINGS_MODULE` and `SECRET_KEY` in the test module. Is there any cleaner way to do the same?

**Comment by tdruez** [comment]
> I had to manually set DJANGO_SETTINGS_MODULE and SECRET_KEY in the test module. Is there any cleaner way to do the same?

That setup is not great, but we'll make it better.
I'm merging the PR as it's getting a bit all over the place.
I'll make some changes and we'll start the packaging process from there :)

**Pull request merged**
